spring.application.name=Gestion_etudiant
server.port=8080

# DATABASE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_etudiant_db
spring.datasource.username=postgres
spring.datasource.password=0674870006

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# IA
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Realm utilisé par l'application
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/gestion_etudiant

# Client d'administration Keycloak
keycloak.admin-client-id=gestion-etudiant-admin
keycloak.admin-client-secret=ioppRKVytPAM6MJtfNg2W2LRIRlIS0P5
keycloak.admin-realm=gestion_etudiant
keycloak.realm=gestion_etudiant
keycloak.server-url=http://localhost:8081

# Groupes
keycloak.groups.teacher=Teacher
keycloak.groups.student=Student

# KAFKA
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topic=gestion-etudiant-events
app.kafka.group-id=gestion-etudiant-group

# GMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soufianebennani01@gmail.com
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true