spring.application.name=Gestion_etudiant
server.port=8080
# DATABASE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_etudiant_db
spring.datasource.username=postgres
spring.datasource.password="0674870006"
#spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#IA
spring.ai.openai.api-key=${OPENAI_API_KEY}

#Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/gestion_etudiant


